config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  devise_for :users
  resources :products do
    member do
      post :favourite
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favourite_product.rb
class FavouriteProduct < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :site
  has_many :favourite_products
  has_many :favourited_by, through: :favourite_products, source: :user
  def self.search(search_term)
    # joins(:site).where("sites.name LIKE ?","%#{search_term}%") 
    # where('products.name like ?',"%#{search_term}%")
    joins(:site).where("sites.name LIKE :search OR products.name LIKE :search",search:"%#{search_term}%") 
  end

  def sample_test
    puts "Product name #{self.name}"
  end

end

app/models/site.rb
class Site < ApplicationRecord
  has_many :products
  def self.search(search_term)
    where('name like ?',"%#{search_term}%")
    # Product.joins(:site).where(sites:{name:"%#{search_term}%"})
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable
  has_many :favourite_products
  has_many :favourites, through: :favourite_products, source: :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters,if: :devise_controller?
  before_action :authenticate_user!
  def after_sign_in_path_for(resource)
    products_path
  end
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:name,:email,:password,:password_confirmation])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  def index
    if params[:search_term]
    # binding.pry
      @products = Product.includes(:site).search(params[:search_term])
      respond_to do |format|
        format.js
      end
    else
      @products = Product.includes(:site).all
      respond_to do |format|
        format.html
      end
    end
  end

  def new
    @product = Product.new
  end

  def create
    binding.pry
    @product = Product.new(product_params)
    @user = current_user
    if @product.save
      # ProductMailer.delay(priority: 20 ,run_at: 5.minutes.from_now).sample_email(@product,current_user)
      # Delayed::Job.enqueue(ProductMailer.sample_email(@product,@user).deliver, :run_at =>  Time.now)
      flash[:notice] = "product saved successfully"
      redirect_to @product
    else
      flash[:alert] = "unable to save product"
      redirect_to products_path
    end
  end

  def show
    @product = Product.find(params[:id])
  end
  
  def favourite
    type = params[:type]
    if type == "favourite"
      @product = Product.find(params[:id])
      current_user.favourites << @product
      ProductMailer.delay(run_at: @product.sale_time - 30.minutes).sample_email(@product,current_user)
      flash[:notice] = "you favourited the #{@product.name}"
      redirect_back(fallback_location: product_path(@product))
    elsif type == "unfavourite"
      @product = Product.find(params[:id])
      current_user.favourites.delete(@product)
      flash[:notice] = "you unfavourited  the #{@product.name}"
      redirect_back(fallback_location: product_path(@product))
    else
      flash[:notice] = "nothing happend"
      redirect_back(fallback_location: product_path(@product))
    end
  end

  private
  def product_params
    params.require(:product).permit(:name,:sale_time).merge(site_id:3)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level) 
    case level.to_sym
      when :info then "alert alert-info"
      when :notice then "alert alert-success"
      when :alert then "alert alert-danger"
      when :warning then "alert alert-warning"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-collapse collapsed" 
      data-toggle="navbar" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Shopper",products_path,class: 'navbar-brand' %>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
          <li class="navbar-brand"><%= current_user.name %></li>
          <li><%= link_to "logout",destroy_user_session_path,method: :delete %></li>
        <% else %>
          <li><%= link_to "login",new_user_session_path %></li>
          <li><%= link_to "signup",new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Emailsend</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <% flash.each do |key,value| %>
      <div class="text-center <%= flash_class(key) %>">
        <%= value %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/products/_product.html.erb
<div class="col-md-4">
  <h4><%= link_to product.name, product_path(product) %></h4>
  <p><%= product.site.name %></p>
  <p><%= product.sale_time.strftime("%A,%b %d,%Y at %I:%m %p") %></p>
</div>

app/views/products/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= form_tag(products_path,method:"get",remote:true) do %>
      <div class="form-group">
        <%= text_field_tag(:search_term,params[:search_term],class: 'form-control') %>
        <%= submit_tag("search",class: 'btn btn-success pull-right') %>
      </div>
    <% end %>
  </div>
</div>
<%= link_to "create product",new_product_path %>
<div class="products">
  <%= render @products %>
</div>

app/views/products/index.js.erb
$(document).ready(function(){
  $('.products').html("<%= j render partial:'products/product', collection:@products %>");
})

app/views/products/new.html.erb
<%= form_for @product,method: :post do |f| %>
  <%= f.text_field :name %>
  <%= f.time_select :sale_time, default: {hour: 9, min: 0} %>
  <%= f.submit "create" %>
<% end %>

app/views/products/show.html.erb
<%= render partial:'products/product', locals: {product:@product} %>
<% if current_user.favourites.include?(@product) %>
  <%= link_to "unfavourite", favourite_product_path(@product,type: "unfavourite"),method: :post %>
<% else %>
  <%= link_to "favourite", favourite_product_path(@product,type: "favourite"),method: :post %>
<% end %>